=== flancer32/dbear/xsd/dem_1.0.0.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema targetNamespace="http://www.flancer64.com/dBEAR/Schema" elementFormDefault="qualified"
		xmlns="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://www.flancer64.com/dBEAR/Schema">


	<complexType name="SetOfAttributes">
		<sequence>
			<element name="attribute" type="tns:Attribute" minOccurs="1" maxOccurs="unbounded">
				<annotation>
					<documentation>Set of the available attributes of the current entity.</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>

	<complexType name="SetOfEntities">
		<sequence>
			<element name="entity" type="tns:Entity" minOccurs="1" maxOccurs="unbounded">
				<annotation>
					<documentation>Set of the available entities in the current namespace.</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>

	<complexType name="ArrayOfRelationEntryReferences">
		<sequence>
			<element name="entryRef" type="tns:RelationEntryReference" minOccurs="1" maxOccurs="unbounded">
				<annotation>
					<documentation>Array of the references to the available entities in the current dBEAR.</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>

	<complexType name="SetOfNamespaces">
		<sequence>
			<element name="namespace" type="tns:Namespace" minOccurs="1" maxOccurs="unbounded">
				<annotation>
					<documentation>Set of the available namespaces in the dBEAR structure.</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>

	<complexType name="SetOfRelations">
		<sequence>
			<element name="relation" type="tns:Relation" minOccurs="1" maxOccurs="unbounded">
				<annotation>
					<documentation>Set of the available relations for the current entity/relation.</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
	<complexType name="SetOfIndexes">
		<sequence>
			<element name="index" type="tns:Index" minOccurs="0" maxOccurs="unbounded">
				<annotation>
					<documentation>Set of the indexes that use current relation entry.</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>

	<complexType name="Attribute">
		<sequence>
			<element name="comment" type="string" minOccurs="0" maxOccurs="1"/>
			<element name="type" type="tns:AttributeTypeChoice" minOccurs="1" maxOccurs="1">
				<annotation>
					<documentation>This attribute type.</documentation>
				</annotation>
			</element>
			<element name="indexes" type="tns:SetOfIndexes" minOccurs="0" maxOccurs="1"/>
		</sequence>
		<attribute name="id" use="required" type="tns:Name">
			<annotation>
				<documentation>
					Attribute name. Must be unique across all other attributes of the entity in the current namespace.
				</documentation>
			</annotation>
		</attribute>
	</complexType>

	<complexType name="AttributeTypeChoice">
		<annotation>
			<documentation>Attribute type can be one of the following:</documentation>
		</annotation>
		<choice>
			<element name="binary" type="tns:AttributeTypeBinary"/>
			<element name="boolean" type="tns:AttributeTypeBoolean"/>
			<element name="datetime" type="tns:AttributeTypeDatetime"/>
			<element name="integer" type="tns:AttributeTypeInteger"/>
			<element name="numeric" type="tns:AttributeTypeNumeric"/>
			<element name="option" type="tns:AttributeTypeOption"/>
			<element name="text" type="tns:AttributeTypeText"/>
		</choice>
	</complexType>

	<complexType name="AttributeType">
		<sequence>
			<element name="isPrimaryKey" type="boolean" default="false" minOccurs="0" maxOccurs="1"/>
			<element name="isNullable" type="boolean" default="false" minOccurs="0" maxOccurs="1">
				<annotation>
					<documentation>
						<![CDATA[
Should we has 'nullable' attribute in XSD?
http://jira.flancer64.com/browse/WF-11?focusedCommentId=12164&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-12164
]]>
					</documentation>
				</annotation>
			</element>
			<element name="isUnique" type="boolean" default="false" minOccurs="0" maxOccurs="1"/>
		</sequence>
	</complexType>

	<complexType name="AttributeTypeBinary">
		<complexContent>
			<extension base="tns:AttributeType">

			</extension>
		</complexContent>
	</complexType>

	<complexType name="AttributeTypeBoolean">
		<complexContent>
			<extension base="tns:AttributeType">

			</extension>
		</complexContent>
	</complexType>

	<complexType name="AttributeTypeDatetime">
		<complexContent>
			<extension base="tns:AttributeType">

			</extension>
		</complexContent>
	</complexType>

	<complexType name="AttributeTypeInteger">
		<complexContent>
			<extension base="tns:AttributeType">
				<sequence>
					<element name="isUnsigned" type="boolean" default="false" minOccurs="0" maxOccurs="1"/>
					<element name="isAutoincrement" type="boolean" default="false" minOccurs="0" maxOccurs="1"/>
				</sequence>
			</extension>
		</complexContent>
	</complexType>

	<complexType name="AttributeTypeNumeric">
		<complexContent>
			<extension base="tns:AttributeType">
				<sequence>
					<element name="isUnsigned" type="boolean" default="false" minOccurs="0" maxOccurs="1"/>
					<element name="precision" type="integer" default="16" minOccurs="0" maxOccurs="1"/>
					<element name="scale" type="integer" default="4" minOccurs="0" maxOccurs="1"/>
				</sequence>
			</extension>
		</complexContent>
	</complexType>

	<complexType name="AttributeTypeOption">
		<complexContent>
			<extension base="tns:AttributeType">

			</extension>
		</complexContent>
	</complexType>

	<complexType name="AttributeTypeText">
		<complexContent>
			<extension base="tns:AttributeType">
				<sequence>
					<element name="length" type="integer" default="255" minOccurs="0" maxOccurs="1"/>
				</sequence>
			</extension>
		</complexContent>
	</complexType>

	<complexType name="Base">
		<annotation>
			<documentation>Database type for the root element of the dBEAR structure.</documentation>
		</annotation>
		<sequence>
			<element name="comment" type="string" minOccurs="0" maxOccurs="1"/>
			<element name="namespaces" type="tns:SetOfNamespaces" minOccurs="1" maxOccurs="1">
				<annotation>
					<documentation>Array of the available namespaces in the dBEAR structure.</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>

	<complexType name="Entity">
		<sequence>
			<element name="comment" type="string" minOccurs="0" maxOccurs="1"/>
			<element name="attributes" type="tns:SetOfAttributes" minOccurs="1" maxOccurs="1">
				<annotation>
					<documentation>Array of the entity's attributes.</documentation>
				</annotation>
			</element>
		</sequence>
		<attribute name="id" use="required" type="tns:Name">
			<annotation>
				<documentation>Entity name. Must be unique across all other entities in the current namespace.</documentation>
			</annotation>
		</attribute>
	</complexType>

	<complexType name="RelationEntryReference">
		<annotation>
			<documentation>Reference to the part of the relation (entity or other relation).</documentation>
		</annotation>
		<sequence>
			<element name="comment" type="string" minOccurs="0" maxOccurs="1"/>
			<element name="namespace" type="tns:Package" minOccurs="1" maxOccurs="1"/>
			<element name="name" type="tns:Name" minOccurs="1" maxOccurs="1"/>
			<element name="alias" type="tns:Name" minOccurs="0" maxOccurs="1"/>
			<element name="indexes" type="tns:SetOfIndexes" minOccurs="0" maxOccurs="unbounded"/>
		</sequence>
		<attribute name="isEntity" type="boolean" default="true" use="optional"/>
	</complexType>

	<complexType name="Index">
		<annotation>
			<documentation>Indexing information for the attribute or relation's entry.</documentation>
		</annotation>
		<sequence>
			<element name="comment" type="string" minOccurs="0" maxOccurs="1"/>
			<element name="position" type="integer" default="0" minOccurs="0" maxOccurs="1"/>
		</sequence>
		<attribute name="id" use="required" type="tns:Name">
			<annotation>
				<documentation>Name of the index that uses this attribute or relation's entry.</documentation>
			</annotation>
		</attribute>
	</complexType>

	<complexType name="Namespace">
		<sequence>
			<element name="comment" type="string" minOccurs="0" maxOccurs="1"/>
			<element name="entities" type="tns:SetOfEntities" minOccurs="0" maxOccurs="1"/>
			<element name="relations" type="tns:SetOfRelations" minOccurs="0" maxOccurs="1">
				<annotation>
					<documentation>Array of the entity's relations.</documentation>
				</annotation>
			</element>
		</sequence>
		<attribute name="id" use="required" type="tns:Package">
			<annotation>
				<documentation>Namespace name. Must be unique across all other namespaces in the dBEAR instance.</documentation>
			</annotation>
		</attribute>
	</complexType>

	<complexType name="Relation">
		<sequence>
			<element name="comment" type="string" minOccurs="0" maxOccurs="1"/>
			<element name="refs" type="tns:ArrayOfRelationEntryReferences" minOccurs="1" maxOccurs="1">
				<annotation>
					<documentation>Set of the entities or other relations that are parts of the current relation.</documentation>
				</annotation>
			</element>
		</sequence>
		<attribute name="id" use="required" type="tns:Name">
			<annotation>
				<documentation>
					Relation name. Must be unique across all other relations of the entity in the current namespace.
				</documentation>
			</annotation>
		</attribute>
	</complexType>

	<simpleType name="AttributeTypeNames">
		<annotation>
			<documentation>Simple types.</documentation>
		</annotation>
		<restriction base="string">
			<enumeration value="binary">
				<annotation>
					<documentation>BLOB, BYTEA, ...</documentation>
				</annotation>
			</enumeration>
			<enumeration value="boolean">
				<annotation>
					<documentation>Logical (true|false)</documentation>
				</annotation>
			</enumeration>
			<enumeration value="datetime">
				<annotation>
					<documentation>DATE, TIME, DATETIME, TIMESTAMP, ...</documentation>
				</annotation>
			</enumeration>
			<enumeration value="integer">
				<annotation>
					<documentation>BYTE, INTEGER, BIGINT, ...</documentation>
				</annotation>
			</enumeration>
			<enumeration value="numeric">
				<annotation>
					<documentation>FLOAT, DECIMAL, ...</documentation>
				</annotation>
			</enumeration>
			<enumeration value="selection">
				<annotation>
					<documentation>ENUM, SELECTION, DICT, ...</documentation>
				</annotation>
			</enumeration>
			<enumeration value="text">
				<annotation>
					<documentation>CHAR, VARCHAR, TEXT, ...</documentation>
				</annotation>
			</enumeration>
		</restriction>
	</simpleType>

	<simpleType name="Name">
		<annotation>
			<documentation>CamelCased alpha-numeric string ("SomeName23").</documentation>
		</annotation>
		<restriction base="string">
			<pattern value="[a-zA-Z0-9_]+"/>
			<minLength value="1"></minLength>
			<maxLength value="255"></maxLength>
			<whiteSpace value="collapse"/>
		</restriction>
	</simpleType>

	<simpleType name="Package">
		<annotation>
			<documentation>Dot-separated alpha-numeric string (Java style is recommended: "com.sun.java.swing.plaf").
			</documentation>
		</annotation>
		<restriction base="string">
			<pattern value="[a-zA-Z0-9\.]+"/>
			<minLength value="1"></minLength>
			<maxLength value="255"></maxLength>
			<whiteSpace value="collapse"/>
		</restriction>
	</simpleType>


	<element name="dBEAR" type="tns:Base"/>

</schema>

=== flancer32/dbear/sample/sample.dem.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:dBEAR
		xmlns:tns="http://www.flancer64.com/dBEAR/Schema"
		xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		xsi:schemaLocation="http://www.flancer64.com/dBEAR/Schema ../xsd/dem_1.0.0.xsd ">
	<tns:namespaces>
		<tns:namespace id="com.flancer32.dbear.sample.core">
			<tns:comment>Base namespace for samples.</tns:comment>
			<tns:entities>
				<tns:entity id="Person">
					<tns:comment>Person basic entity with 2 attributes.</tns:comment>
					<tns:attributes>
						<tns:attribute id="NameFirst">
							<tns:type>
								<tns:text/>
							</tns:type>
						</tns:attribute>
						<tns:attribute id="NameLast">
							<tns:type>
								<tns:text/>
							</tns:type>
						</tns:attribute>
						<tns:attribute id="Gender">
							<tns:type>
								<tns:text>
									<tns:isNullable>false</tns:isNullable>
									<tns:isUnique>false</tns:isUnique>
									<tns:length>1</tns:length>
								</tns:text>
							</tns:type>
						</tns:attribute>
					</tns:attributes>
				</tns:entity>
			</tns:entities>
		</tns:namespace>
		<tns:namespace id="com.flancer32.dbear.sample.auth">
			<tns:comment>Another namespace with authentication related entities.</tns:comment>
			<tns:entities>
				<tns:entity id="AuthMethod">
					<tns:comment>Authentication methods can be used in the current application (username and password, SMS code, etc.).</tns:comment>
					<tns:attributes>
						<tns:attribute id="Name">
							<tns:type>
								<tns:text/>
							</tns:type>
						</tns:attribute>
					</tns:attributes>
				</tns:entity>
			</tns:entities>
			<tns:relations>
				<tns:relation id="PersonAuthMethod">
					<tns:comment>Each Person can be authenticated by one ore more methods.</tns:comment>
					<tns:refs>
						<tns:entryRef>
							<tns:id>AuthMethod</tns:id>
						</tns:entryRef>
						<tns:entryRef>
							<tns:namespace>com.flancer32.dbear.sample.core</tns:namespace>
							<tns:id>Person</tns:id>
							<!-- Uncomment unique index to allow one only authentication method per person. -->
							<tns:indexes>
								<tns:index id="UniquePerson">
									<tns:comment>One only Method per Person is allowed.</tns:comment>
								</tns:index>
							</tns:indexes>
						</tns:entryRef>
					</tns:refs>
				</tns:relation>
			</tns:relations>
		</tns:namespace>
	</tns:namespaces>
</tns:dBEAR>

=== flancer32/dbear/convertor/sample2.dem.xml
<?xml version="1.0" encoding="UTF-8"?>
<dbear:dBEAR xmlns:dbear="http://www.flancer64.com/dBEAR/Schema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xsi:schemaLocation="http://www.flancer64.com/dBEAR/Schema ../../xsd/dem_1.0.0.xsd ">
    <dbear:comment>Second iteration in the domain data development.</dbear:comment>
    <dbear:namespaces>
        <dbear:namespace id="com.flancer32.dbear.sample.core">
            <dbear:comment>Add attribute to the existing Entity.</dbear:comment>
            <dbear:entities>
                <dbear:entity id="Person">
                    <dbear:attributes>
                        <dbear:attribute id="Gender">
                            <dbear:type>
                                <dbear:text>
                                    <dbear:isNullable>false</dbear:isNullable>
                                    <dbear:isUnique>false</dbear:isUnique>
                                    <dbear:length>1</dbear:length>
                                </dbear:text>
                            </dbear:type>
                        </dbear:attribute>
                    </dbear:attributes>
                </dbear:entity>
            </dbear:entities>
        </dbear:namespace>
        <dbear:namespace id="com.flancer32.dbear.sample.auth">
            <dbear:comment>Another namespace with authentication related entities.</dbear:comment>
            <dbear:entities>
                <dbear:entity id="AuthMethod">
                    <dbear:comment>Authentication methods can be used in the current application (username and password, SMS code, etc.).</dbear:comment>
                    <dbear:attributes>
                        <dbear:attribute id="Name">
                            <dbear:type>
                                <dbear:text/>
                            </dbear:type>
                        </dbear:attribute>
                    </dbear:attributes>
                </dbear:entity>
            </dbear:entities>
            <dbear:relations>
                <dbear:relation id="Person_AuthMethod">
                    <dbear:comment>Each Person can be authenticated by one ore more methods.</dbear:comment>
                    <dbear:refs>
                        <dbear:entryRef>
                            <dbear:id>AuthMethod</dbear:id>
                        </dbear:entryRef>
                        <dbear:entryRef>
                            <dbear:namespace>com.flancer32.dbear.sample.core</dbear:namespace>
                            <dbear:id>Person</dbear:id>
                            <!-- Uncomment unique index to allow one only authentication method per person. -->
                            <dbear:indexes>
                                <dbear:index id="UniquePerson">
                                    <dbear:comment>One only Method per Person is allowed.</dbear:comment>
                                </dbear:index>
                            </dbear:indexes>
                        </dbear:entryRef>
                    </dbear:refs>
                </dbear:relation>
            </dbear:relations>
        </dbear:namespace>
    </dbear:namespaces>
</dbear:dBEAR>
